%% ================== Pack baseline metric row ==================
function row = pack_row(model_name, type_name, crps, naps, mrae, point_metrics, interval_metrics)

    row = struct( ...
        'Model', model_name, ...
        'Type', type_name, ...
        'CRPS', crps, ...
        'NAPS', naps, ...
        'MRAE', mrae, ...
        'MAE', point_metrics.MAE, ...
        'MAPE', point_metrics.MAPE);

    varNames = interval_metrics.Properties.VariableNames;

    for j = 1:numel(varNames)
        row.(varNames{j}) = interval_metrics{1, j};
    end
end